# --- Servidor ---
server.port=${SERVER_PORT:8081}
spring.application.name=proxy-service

# --- KAFKA CONFIGURATION ---
spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:192.168.194.250:9092}

# IMPORTANTE: Mantengo TU grupo, no uses el de tu amigo
spring.kafka.consumer.group-id=${KAFKA_GROUP_ID:elcomandante18}

spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer

# Auto startup true para escuchar eventos
spring.kafka.listener.auto-startup=true

# --- REDIS CONFIGURATION ---
spring.data.redis.host=${REDIS_HOST:192.168.194.250}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

# --- BACKEND LINK ---
backend.url=${BACKEND_URL:http://localhost:8080}

# --- LOGGING ---
logging.level.root=INFO
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=INFO

# Ajustado a TU paquete
logging.level.com.tp2025.proxy=DEBUG